name: "health_care"
version: "1.0.0"


profile: "health_care"


model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
docs-paths: ["docs"]

clean-targets:
  - "target"
  - "dbt_packages"


models:
  health_care:
    +materialized: view
    +meta:
      owner: "@statistahealth_analytics"
    marts:
      +materialized: table
      +access: public
      catalog: "{{ 'gold_production' if (target.name == 'production') else 'gold_staging' if (target.name == 'staging') else target.database }}"
      schema: "{{ 'health_care' if (target.name == 'production' or target.name == 'staging') else target.schema }}"

data_tests:
  health_care:
    +severity: warn

restrict-access: True