name: "product"
version: "1.0.0"

# This setting configures which "profile" dbt uses for this project.
profile: "product"

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
docs-paths: ["docs"]

clean-targets:
  - "target"
  - "dbt_packages"

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

models:
  health_care:
    +materialized: view
    +meta:
      owner: "@statistaproduct_analytics"
    marts:
      +materialized: table
      +access: public
      catalog: "{{ 'gold_production' if (target.name == 'production') else 'gold_staging' if (target.name == 'staging') else target.database }}"
      schema: "{{ 'product' if (target.name == 'production' or target.name == 'staging') else target.schema }}"

data_tests:
  health_care:
    +severity: warn

restrict-access: True